### ISSUE TITLE
ImportError: DLL load failed: Не найден указанный модуль.

### ISSUE THREAD

**Issue by pers972** [matham/thorcam#9]
Hello. After importing 'from thorcam.camera import ThorCam' getting this error:
 Traceback (most recent call last):
  File "C:/Users/Роман/PycharmProjects/camera/main.py", line 6, in <module>
    from thorcam.camera import ThorCam
  File "C:\Users\Роман\PycharmProjects\camera\venv\lib\site-packages\thorcam\camera.py", line 32, in <module>
    from ffpyplayer.pic import Image
ImportError: DLL load failed: Не найден указанный модуль.

**Comment by matham** [comment]
Sorry, this seems like an issue with your system and I can't really help.
